Repository GSM-MSG/GCMS-iOS, pull requests merged in 2022-05, with the labels that each got.

#72 🔀 :: Fastlane commandLine 구축
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
Labels: 3️⃣Priority: Low, 🌏 Deploy

#73 🔀 :: 구글 로그인 UI, 애플 게스트 로그인 로직
  .package.resolved
  Service/Sources/Data/DataSource/Local/UserDefaults/UserDefaultsLocal.swift
  Service/Sources/Domain/UseCases/Auth/CheckIsLoginedUseCase.swift
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Derived/Sources/Assets+GCMS.swift
  iOS/Resources/GoogleService-Info.plist
  iOS/Resources/Images.xcassets/GCMS_GoogleLogo.imageset/Contents.json
  iOS/Resources/Images.xcassets/GCMS_GoogleLogo.imageset/Google_"G"_Logo.svg-1.png
  iOS/Resources/Images.xcassets/GCMS_GoogleLogo.imageset/Google_"G"_Logo.svg-2.png
  iOS/Resources/Images.xcassets/GCMS_GoogleLogo.imageset/Google_"G"_Logo.svg.png
  iOS/Sources/Application/AppDelegate.swift
  iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
  iOS/Sources/Application/DI/Assembly/VCAssembly.swift
  iOS/Sources/Application/Flow/Flows/OnBoarding/OnBoardingFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Presentation/Scene/Auth/Login/Reactor/LoginReactor.swift
  iOS/Sources/Presentation/Scene/Auth/Login/VC/LoginVC.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/VC/OnBoardingVC.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/Certification/Reactor/CertificationReactor.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/Certification/VC/CertificationVC.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/Reactor/SignUpReactor.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/VC/SignUpVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
  iOS/Support/GCMS.entitlements
  iOS/Support/Info.plist
  iOS/Tests/Reactor/LoginReactorSpec.swift
Labels: 1️⃣Priority: High, ✨ Feature

#74 🔀 :: OAuth 통신
  Service/Sources/DI/UseCaseAssembly.swift
  Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Auth/Login/LoginRequest.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Auth/Register/RegisterRequest.swift
  Service/Sources/Data/DataSource/Remote/DataSource/AuthRemote.swift
  Service/Sources/Data/Repositories/DefaultAuthRepository.swift
  Service/Sources/Domain/Repositories/AuthRepository.swift
  Service/Sources/Domain/UseCases/Auth/CheckIsLoginedUseCase.swift
  Service/Sources/Domain/UseCases/Auth/CheckIsVerifiedUseCase.swift
  Service/Sources/Domain/UseCases/Auth/LoginUseCase.swift
  Service/Sources/Domain/UseCases/Auth/RegisterUseCase.swift
  Service/Sources/Domain/UseCases/Auth/SendVerifyUseCase.swift
  iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Tests/Mock/MockFailureAuthRepository.swift
  iOS/Tests/Mock/MockSuccessAuthRepository.swift
Labels: 1️⃣Priority: High, ✨ Feature, 📬 API

#75 🔀 :: Inject적용 및 catch error
  .package.resolved
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/DetailClub/DetailClubDTO.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/DetailClub/DetailClubResponse.swift
  Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/Excutable.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Project.swift
  iOS/Sources/Application/SceneDelegate.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/EditorialClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/FreedomClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/MajorClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/MemberAppend/Reactor/MemberAppendReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/VC/MyPageVC.swift
Labels: ⚙ Setting, 2️⃣Priority: Medium, 🐞 BugFix, 🔨 Refactor

#77 🔀 :: HomeUI 변경
  Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
  Service/Sources/Domain/Entities/ClubType.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/EditorialClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/FreedomClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/MajorClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
Labels: 0️⃣Priority: Critical, ✨ Feature, 🔨 Refactor

#78 Refactor
  .package.resolved
  iOS/Sources/Presentation/Scene/Auth/Common/View/WaveView.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/VC/OnBoardingVC.swift
Labels: 2️⃣Priority: Medium, 🔨 Refactor

#80 🔀 :: 방과후 UI
  iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
  iOS/Sources/Application/DI/Assembly/VCAssembly.swift
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/Reactor/AfterSchoolReactor.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/SearchFilter/Reactor/SearchFilterReactor.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/SearchFilter/VC/SearchFilterVC.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/SearchFilter/View/FilterModalSegmentedControl.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/SearchFilter/View/SegmentHeaderLabel.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/VC/AfterSchoolVC.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/View/Cell/AfterSchoolTableViewCell.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/View/SemiBoldTextLabel.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
  iOS/Sources/Presentation/Scene/Main/MemberAppend/VC/MemberAppendVC.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Reactor/MyPageReactor.swift
Labels: 3️⃣Priority: Low, ✨ Feature

#81 🔀 :: 관련 링크 정책 변경에 따라서 타입 변경
  iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/VC/SecondNewClubVC.swift
Labels: 2️⃣Priority: Medium, 📬 API

#83 🔀 :: AfterSchoolAPI
  Service/Sources/DI/RepositoryAssembly.swift
  Service/Sources/DI/UseCaseAssembly.swift
  Service/Sources/Data/DataSource/Remote/API/AfterSchoolAPI.swift
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/AfterSchool/AfterSchoolDTO.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/AfterSchool/AfterSchoolList/AfterSchoolListResponse.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/ClubList/ClubListDTO.swift
  Service/Sources/Data/DataSource/Remote/DataSource/AfterSchoolRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
  Service/Sources/Data/Repositories/DefaultAfterSchoolRepository.swift
  Service/Sources/Domain/Entities/AfterSchool.swift
  Service/Sources/Domain/Entities/AfterSchoolQuery.swift
  Service/Sources/Domain/Entities/AfterSchoolSeason.swift
  Service/Sources/Domain/Entities/AfterSchoolWeek.swift
  Service/Sources/Domain/Repositories/AfterSchoolRepository.swift
  Service/Sources/Domain/UseCases/AfterSchool/ApplyAfterSchoolUseCase.swift
  Service/Sources/Domain/UseCases/AfterSchool/CancelAfterSchoolUseCase.swift
  Service/Sources/Domain/UseCases/AfterSchool/FetchAfterSchoolListUseCase.swift
  Service/Sources/Domain/UseCases/AfterSchool/FetchFindAfterSchoolUseCase.swift
Labels: 0️⃣Priority: Critical, ✨ Feature, 📬 API

#84 🔀 :: GuestSignin feature
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/VC/OnBoardingVC.swift
Labels: 1️⃣Priority: High, 🌏 Deploy, ✨ Feature

#86 🔀 :: 용도에 맞게 폴더 분리
  Service/Sources/Domain/Enums/AfterSchoolSeason.swift
  Service/Sources/Domain/Enums/AfterSchoolWeek.swift
  Service/Sources/Domain/Enums/ClubType.swift
  Service/Sources/Domain/Enums/MemberScope.swift
  Service/Sources/Domain/Parameters/AfterSchoolQuery.swift
  Service/Sources/Domain/Parameters/ClubRequestQuery.swift
Labels: 3️⃣Priority: Low, ⚙ Setting

#85 🔀 :: Redesign/club member
  iOS/Project.swift
  iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Application/Flow/Flows/OnBoarding/OnBoardingFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Application/SceneDelegate.swift
  iOS/Sources/Presentation/Base/BaseTableViewHeaderFooter.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/Reactor/ClubMemberReactor.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/VC/ClubMemberVC.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/ApplicantCell.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/MemberHeaderView.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/StatusMemberCell.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/View/ExpandableMemberSection.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/Reactor/ClubStatusReactor.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/VC/ClubStatusVC.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/VC/Items/ClubApplicantsVC.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/VC/Items/ClubMemberVC.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/View/Cell/Section/ApplicantSection.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/View/Cell/Section/StatusMemberSection.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/View/ClubStatusSegmentedControl.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift
  iOS/Sources/Presentation/Utils/Extensions/UIKit/UIView/UIViewExt.swift
  iOS/Support/Info.plist
Labels: 1️⃣Priority: High, ✨ Feature, 🔨 Refactor
