Repository GSM-MSG/GCMS-iOS, pull requests merged in 2022-04, with the labels that each got.

#56 🔀 :: HomeVC segmentedControl -> tabbar
  .package.resolved
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Sources/Application/DI/Container/AppDI.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/EditorialClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/FreedomClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/MajorClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
Labels: 3️⃣Priority: Low, 🔨 Refactor

#58 🔀 :: 실패할때 전용 Alert Step
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
Labels: 2️⃣Priority: Medium, ✨ Feature

#59 🔀 :: 동아리 개설 페이지
  .package.resolved
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Derived/Sources/Assets+GCMS.swift
  iOS/Resources/Images.xcassets/GCMS_Editorial.imageset/Contents.json
  iOS/Resources/Images.xcassets/GCMS_Editorial.imageset/Editorial-1.svg
  iOS/Resources/Images.xcassets/GCMS_Editorial.imageset/Editorial-2.svg
  iOS/Resources/Images.xcassets/GCMS_Editorial.imageset/Editorial.svg
  iOS/Resources/Images.xcassets/GCMS_Freedom.imageset/Contents.json
  iOS/Resources/Images.xcassets/GCMS_Freedom.imageset/Freedom-1.svg
  iOS/Resources/Images.xcassets/GCMS_Freedom.imageset/Freedom-2.svg
  iOS/Resources/Images.xcassets/GCMS_Freedom.imageset/Freedom.svg
  iOS/Resources/Images.xcassets/GCMS_Major.imageset/Contents.json
  iOS/Resources/Images.xcassets/GCMS_Major.imageset/Major-1.svg
  iOS/Resources/Images.xcassets/GCMS_Major.imageset/Major-2.svg
  iOS/Resources/Images.xcassets/GCMS_Major.imageset/Major.svg
  iOS/Sources/Application/DI/Container/AppDI.swift
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Presentation/Scene/Login/VC/LoginVC.swift
  iOS/Sources/Presentation/Scene/Main/Accept/Reactor/AcceptReactor.swift
  iOS/Sources/Presentation/Scene/Main/Accept/VC/AcceptVC.swift
  iOS/Sources/Presentation/Scene/Main/Accept/View/Cell/AcceptCell.swift
  iOS/Sources/Presentation/Scene/Main/Accept/View/Section/ApplicantSection.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/VC/ClubStatusVC.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/View/Cell/StatusMemberCell.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/Cell/ClubMemberCell.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/HeaderLabel.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/Section/ClubMemberSection.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/EditorialClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/FreedomClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/MajorClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/View/ClubTypeSegmentedControl.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/VC/FirstNewClubVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/VC/NewClubVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/VC/SecondNewClubVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/VC/ThirdNewClubVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/View/ClubTypeCardButton.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/View/NewClubAppendButton.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/View/NewClubStepView.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/View/NewClubSteppedProgressBar.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/View/NewClubTextField.swift
  iOS/Sources/Presentation/Utils/Extensions/UIKit/UILabel/UILabelExt.swift
  iOS/Sources/Presentation/Utils/Extensions/UIKit/UIView/UIViewExt.swift
Labels: 1️⃣Priority: High, ✨ Feature

#60 🔀 :: 로그아웃 기능
  Service/Sources/Data/DataSource/Local/Keychain/KeychainLocal.swift
  Service/Sources/Data/Repositories/DefaultAuthRepository.swift
  Service/Sources/Data/UseCases/RemoveMe1.swift
  Service/Sources/Domain/Repositories/AuthRepository.swift
  Service/Sources/Domain/UseCases/Auth/LogoutUseCase.swift
  Service/Sources/ServiceDI.swift
  iOS/Sources/Application/DI/Container/AppDI.swift
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Reactor/MyPageReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/VC/MyPageVC.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/View/UserProfileView.swift
  iOS/Tests/Mock/MockFailureAuthRepository.swift
  iOS/Tests/Mock/MockSuccessAuthRepository.swift
Labels: 2️⃣Priority: Medium, ✨ Feature, 🔨 Refactor

#62 Feat/SignUp
  .package.resolved
  Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
  Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
  Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ImageRemote.swift
  Service/Sources/Domain/Error/GCMSError.swift
  Service/Sources/Domain/Repositories/UserRepository.swift
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Sources/Application/DI/Container/AppDI.swift
  iOS/Sources/Application/Flow/Flows/OnBoarding/OnBoardingFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Presentation/Scene/Auth/Common/View/WaveView.swift
  iOS/Sources/Presentation/Scene/Auth/Login/Reactor/LoginReactor.swift
  iOS/Sources/Presentation/Scene/Auth/Login/VC/LoginVC.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/VC/OnBoardingVC.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/Certification/Reactor/CertificationReactor.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/Certification/VC/CertificationVC.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/Reactor/SignUpReactor.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/VC/SignUpVC.swift
  iOS/Sources/Presentation/Scene/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Support/Info.plist
Labels: 1️⃣Priority: High, ✨ Feature

#64 🔀 :: DI 로직 변경
  Service/Sources/DI/RepositoryAssembly.swift
  Service/Sources/DI/UseCaseAssembly.swift
  Service/Sources/ServiceDI.swift
  iOS/Sources/Application/AppDelegate.swift
  iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
  iOS/Sources/Application/DI/Assembly/VCAssembly.swift
  iOS/Sources/Application/DI/Container/AppDI.swift
Labels: 3️⃣Priority: Low, 🔨 Refactor

#65 🔀 :: 동아리 멤버 관리 페이지
  Service/Sources/DI/UseCaseAssembly.swift
  iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/Reactor/ClubStatusReactor.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/VC/ClubStatusVC.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/VC/Items/ClubApplicantsVC.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/VC/Items/ClubMemberVC.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/View/Cell/ApplicantCell.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/View/Cell/Section/ApplicantSection.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/View/Cell/Section/StatusMemberSection.swift
  iOS/Sources/Presentation/Scene/Main/ClubStatus/View/Cell/StatusMemberCell.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Support/Info.plist
Labels: 3️⃣Priority: Low, 🔨 Refactor

#66 Refactor/user api
  Service/Sources/DI/UseCaseAssembly.swift
  Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/User/My/JoinedClubDTO.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/User/My/JoinedClubResponse.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/User/My/UserMyProfileResponse.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/User/My/UserProfileResponse.swift
  Service/Sources/Data/DataSource/Remote/DataSource/UserRemote.swift
  Service/Sources/Data/Repositories/DefaultUserRepository.swift
  Service/Sources/Domain/Repositories/UserRepository.swift
  Service/Sources/Domain/UseCases/User/ClubExitUseCase.swift
  Service/Sources/Domain/UseCases/User/FetchProfileUseCase.swift
  Service/Sources/Domain/UseCases/User/SearchUserUseCase.swift
  Service/Sources/Domain/UseCases/User/UpdateProfileImageUseCase.swift
Labels: 🙋‍♂️ Question, 2️⃣Priority: Medium, 📬 API, 🔨 Refactor

#67 🔀 :: ARC 에러 해결
  Service/Sources/DI/RepositoryAssembly.swift
  Service/Sources/DI/UseCaseAssembly.swift
  iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
  iOS/Sources/Application/DI/Assembly/VCAssembly.swift
  iOS/Sources/Presentation/Scene/Auth/Login/Reactor/LoginReactor.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/Certification/VC/CertificationVC.swift
Labels: 0️⃣Priority: Critical, 🐞 BugFix

#70 🔀 :: Feat/parked text field
  .package.resolved
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Sources/Presentation/Scene/Auth/Common/View/WaveView.swift
  iOS/Sources/Presentation/Scene/Auth/Login/Reactor/LoginReactor.swift
  iOS/Sources/Presentation/Scene/Auth/Login/VC/LoginVC.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/Certification/Reactor/CertificationReactor.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/Certification/VC/CertificationVC.swift
  iOS/Sources/Presentation/Scene/Auth/SignUp/VC/SignUpVC.swift
Labels: 3️⃣Priority: Low, 🔨 Refactor
