Repository GSM-MSG/GCMS-iOS, pull requests merged in 2022-03, with the labels that each got.

#14 🔀 :: 동아리 리스트, 동아리 소개 페이지
  .package.resolved
  Service/Sources/Domain/Entities/ClubList.swift
  Service/Sources/Domain/Entities/DetailClub.swift
  Service/Sources/Domain/Entities/User.swift
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Derived/Sources/Assets+GCMS.swift
  iOS/Resources/Colors.xcassets/Gray/GCMS_Gray1.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray/GCMS_Gray2.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray/GCMS_Gray3.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray/GCMS_Gray4.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray/GCMS_Gray5.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray/GCMS_Gray6.colorset/Contents.json
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Presentation/Scene/Main/Common/Cell/ClubListCell.swift
  iOS/Sources/Presentation/Scene/Main/Common/ClubView.swift
  iOS/Sources/Presentation/Scene/Main/Common/Section/ClubListSection.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/Cell/MemberCell.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/HeaderLabel.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/Section/MemberSection.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/UserHorizontalView.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/View/Layout/GCMSLayout.swift
  iOS/Sources/Presentation/Scene/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/OnBoarding/VC/OnBoardingVC.swift
  iOS/Sources/Presentation/Utils/Extensions/UIKit/UINavigation/UINavigationExt.swift
Labels: 0️⃣Priority: Critical, ✨ Feature

#19 🔀 :: Image API
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ImageRemote.swift
  Service/Sources/Data/Repositories/DefaultImageRepository.swift
  Service/Sources/Domain/Repositories/ImageRepository.swift
Labels: 0️⃣Priority: Critical, ✨ Feature, 📬 API

#20 🔀 :: UserAPI
  Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
  Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/NewClub/NewClubRequest.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/User/Search/UserSearchResponse.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/User/UserDTO.swift
  Service/Sources/Data/DataSource/Remote/DataSource/UserInfoResponse.swift
  Service/Sources/Data/DataSource/Remote/DataSource/UserRemote.swift
  Service/Sources/Data/Repositories/DefaultUserRepository.swift
  Service/Sources/Data/Repositories/NoticeDTO.swift
  Service/Sources/Data/Repositories/UserNoticeResponse.swift
  Service/Sources/Domain/Entities/Notice.swift
  Service/Sources/Domain/Entities/User.swift
  Service/Sources/Domain/Repositories/UserRepository.swift
  Service/Sources/Domain/UseCases/AcceptClubUseCase.swift
  Service/Sources/Domain/UseCases/EditProfileUseCase.swift
  Service/Sources/Domain/UseCases/FetchNoticeListUseCase.swift
  Service/Sources/Domain/UseCases/FetchUserInfoUseCase.swift
  Service/Sources/Domain/UseCases/RejectClubUseCase.swift
  Service/Sources/Domain/UseCases/RemoveMe10.swift
  Service/Sources/Domain/UseCases/SearchUserUseCase.swift
  iOS/Sources/Presentation/Scene/Main/Common/Cell/ClubListCell.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/Cell/MemberCell.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/UserHorizontalView.swift
  iOS/Sources/Presentation/Scene/Main/MemberAppend/Reactor/MemberAppendReactor.swift
  iOS/Sources/Presentation/Scene/Main/MemberAppend/VC/MemberAppendVC.swift
  iOS/Sources/Presentation/Scene/Main/MemberAppend/View/Cell/StudentCell.swift
  iOS/Sources/Presentation/Utils/Extensions/UIKit/UINavigation/UINavigationExt.swift
Labels: 0️⃣Priority: Critical, ✨ Feature, 📬 API

#22 🔀 :: LoginUseCase
  Service/Sources/Domain/UseCases/LoginUseCase.swift
Labels: 1️⃣Priority: High, ✨ Feature, 📬 API

#25 🔀 ::VC, Reactor에 Activity Indicator
  .package.resolved
  Service/Sources/Data/DataSource/Local/UserDefaults/UserDefaultsLocal.swift
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Resources/Lottie/GCMS-Indicator.json
  iOS/Sources/Application/SceneDelegate.swift
  iOS/Sources/Presentation/Base/BaseVC.swift
  iOS/Sources/Presentation/Scene/Main/Alarm/Reactor/AlarmReactor.swift
  iOS/Sources/Presentation/Scene/Main/Alarm/VC/AlarmVC.swift
  iOS/Sources/Presentation/Scene/Main/Common/Cell/ClubListCell.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/Cell/MemberCell.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/UserHorizontalView.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
  iOS/Sources/Presentation/Scene/Main/MemberAppend/Reactor/MemberAppendReactor.swift
  iOS/Sources/Presentation/Scene/Main/MemberAppend/VC/MemberAppendVC.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Management/Reactor/ManagementReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Management/VC/ManagementVC.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Reactor/MyPageReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/VC/MyPageVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/VC/NewClubVC.swift
  iOS/Sources/Presentation/Scene/Main/Notice/Reactor/NoticeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Notice/VC/NoticeVC.swift
  iOS/Sources/Presentation/Scene/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/OnBoarding/VC/OnBoardingVC.swift
  iOS/Sources/Presentation/Utils/Extensions/Rx/ASAuthorizationAppleID+Rx/ASAuthorizationAppleID+Rx.swift
  iOS/Sources/Presentation/Utils/Extensions/Rx/ASAuthorizationControllerProxy/ASAuthorizationControllerProxy.swift
  iOS/Sources/Presentation/Utils/Extensions/UIKit/UITextField/UITextFieldExt.swift
  iOS/Support/GCMS.entitlements
  iOS/Support/Info.plist
Labels: 0️⃣Priority: Critical, ✨ Feature

#29 🔀 :: 신청자 수락/거절 페이지
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Presentation/Scene/Main/Accept/Reactor/AcceptReactor.swift
  iOS/Sources/Presentation/Scene/Main/Accept/VC/AcceptVC.swift
  iOS/Sources/Presentation/Scene/Main/Accept/View/Cell/AcceptCell.swift
  iOS/Sources/Presentation/Scene/Main/Notice/Reactor/NoticeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Notice/VC/NoticeVC.swift
Labels: 0️⃣Priority: Critical, ✨ Feature

#30 🔀 :: Service Layer DI
  Service/Sources/Domain/UseCases/Auth/LoginUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchClubListUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchDetailClubUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchManagementClubUseCase.swift
  Service/Sources/Domain/UseCases/User/AcceptClubUseCase.swift
  Service/Sources/Domain/UseCases/User/FetchNoticeListUseCase.swift
  Service/Sources/Domain/UseCases/User/FetchUserInfoUseCase.swift
  Service/Sources/Domain/UseCases/User/RejectClubUseCase.swift
  Service/Sources/Domain/UseCases/User/SearchUserUseCase.swift
  Service/Sources/ServiceDI.swift
Labels: 0️⃣Priority: Critical, ⚙ Setting, 📬 API

#31 🔀 :: Reactor UseCases Dependency Injection
  iOS/Sources/Application/DI/Container/AppDI.swift
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Presentation/Scene/Main/Alarm/Reactor/AlarmReactor.swift
  iOS/Sources/Presentation/Scene/Main/ClubManagement/Reactor/ClubManagementReactor.swift
  iOS/Sources/Presentation/Scene/Main/ClubManagement/VC/ClubManagementVC.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/MemberAppend/Reactor/MemberAppendReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Management/Reactor/ManagementReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Reactor/MyPageReactor.swift
  iOS/Sources/Presentation/Scene/Main/Notice/Reactor/NoticeReactor.swift
  iOS/Sources/Presentation/Scene/OnBoarding/Reactor/OnBoardingReactor.swift
Labels: 0️⃣Priority: Critical, ✨ Feature, 📬 API

#32 🔀 :: Apple Signing configuration
  Tuist/ProjectDescriptionHelpers/Settings.swift
  iOS/Sources/Presentation/Base/BaseVC.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/VC/MyPageVC.swift
  iOS/Sources/Presentation/Scene/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/OnBoarding/VC/OnBoardingVC.swift
Labels: 0️⃣Priority: Critical, ✨ Feature, 📬 API

#34 🔀 :: Image API
  Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ImageRemote.swift
  Service/Sources/Data/Repositories/DefaultImageRepository.swift
  Service/Sources/Domain/Repositories/ImageRepository.swift
  Service/Sources/Domain/UseCases/Club/CreateNewClubUseCase.swift
  Service/Sources/Domain/UseCases/User/EditProfileUseCase.swift
Labels: 0️⃣Priority: Critical, 📬 API

#33 🔀 :: Club API Routing
  Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/ClubMembers/ClubMembersResponse.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/Notification/NotificationRequest.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/WaitList/ClubWaitListResponse.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/User/UserInfo/UserInfoResponse.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ClubRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/UserRemote.swift
  Service/Sources/Data/Repositories/DefaultClubRepository.swift
  Service/Sources/Data/Repositories/DefaultUserRepository.swift
  Service/Sources/Domain/Entities/NoticeType.swift
  Service/Sources/Domain/Repositories/ClubRepository.swift
  Service/Sources/Domain/Repositories/UserRepository.swift
  Service/Sources/Domain/UseCases/Club/ClubEndUseCase.swift
  Service/Sources/Domain/UseCases/Club/ClubNotificationUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchClubMembersUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchClubWaitListUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchDetailClubUseCase.swift
  Service/Sources/Domain/UseCases/Club/JoinClubUseCase.swift
  Service/Sources/Domain/UseCases/Club/UserAcceptUseCase.swift
  Service/Sources/Domain/UseCases/Club/UserRejectUseCase.swift
  Service/Sources/Domain/UseCases/User/AcceptClubUseCase.swift
  Service/Sources/Domain/UseCases/User/RejectClubUseCase.swift
Labels: 0️⃣Priority: Critical, 📬 API

#35 🔀 :: Deploy Setting
  Tuist/ProjectDescriptionHelpers/DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/Excutable.swift
  Tuist/ProjectDescriptionHelpers/OrganizationName.swift
  Tuist/ProjectDescriptionHelpers/Settings.swift
  iOS/Derived/Sources/Plists+GCMS.swift
  iOS/Resources/GoogleService-Info.plist
Labels: 0️⃣Priority: Critical, ⚙ Setting, 🌏 Deploy

#38 🔀 :: Auth API UseCases Dependency Injection
  Service/Sources/ServiceDI.swift
Labels: 0️⃣Priority: Critical, 📬 API

#40 🔀 :: 레거시 구조 변경
  iOS/Sources/Application/DI/Container/AppDI.swift
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Presentation/Scene/Main/Accept/Reactor/AcceptReactor.swift
  iOS/Sources/Presentation/Scene/Main/Accept/VC/AcceptVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Management/Reactor/ManagementReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Management/VC/ManagementVC.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Reactor/MyPageReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/VC/MyPageVC.swift
Labels: 0️⃣Priority: Critical, 🐞 BugFix

#41 🔀 :: JWT Plugin expiredAt 대응
  Service/Sources/Data/DataSource/Local/Keychain/Keychain.swift
  Service/Sources/Data/DataSource/Local/Keychain/KeychainLocal.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Token/TokenDTO.swift
  Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
  Service/Sources/Data/DataSource/Remote/Plugin/JWTPlugin.swift
  Service/Sources/Data/Repositories/DefaultAuthRepository.swift
  Service/Sources/Data/Utils/DateUtil.swift
  Service/Sources/Data/Utils/RemoveMe0.swift
Labels: 1️⃣Priority: High, ✨ Feature, 📬 API

#42 🔀 :: Delete Sign in with Apple
  iOS/Support/GCMS.entitlements
Labels: 0️⃣Priority: Critical, ⚙ Setting, 🌏 Deploy

#44 🔀 :: AppFlow 구조 변경
  iOS/Resources/LaunchScreen.storyboard
  iOS/Sources/Application/Flow/AppFlow.swift
  iOS/Sources/Application/SceneDelegate.swift
Labels: 2️⃣Priority: Medium, ✨ Feature, 🔨 Refactor

#46 🔀 :: Google Signin remove in dependency
  .package.resolved
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Sources/Application/AppDelegate.swift
  iOS/Sources/Presentation/Scene/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/OnBoarding/VC/OnBoardingVC.swift
Labels: 3️⃣Priority: Low, ⚙ Setting, 🌏 Deploy

#48 🔀:: JWTPlugin이 Token을 받으면 expiredAt도 keyChain에 저장
  Service/Sources/Data/DataSource/Remote/Plugin/JWTPlugin.swift
Labels: 3️⃣Priority: Low, 📬 API, 🔨 Refactor

#49 🔀 :: Login 화면UI, 로직 변경
  .package.resolved
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Derived/Sources/Assets+GCMS.swift
  iOS/Resources/Colors.xcassets/GCMS_ThemeColor.colorset/Contents.json
  iOS/Resources/Images.xcassets/GCMS_NewClubPlaceholder.imageset/Contents.json
  iOS/Resources/Images.xcassets/GCMS_NewClubPlaceholder.imageset/placeholder-1.svg
  iOS/Resources/Images.xcassets/GCMS_NewClubPlaceholder.imageset/placeholder-2.svg
  iOS/Sources/Presentation/Scene/Login/Reactor/LoginReactor.swift
  iOS/Sources/Presentation/Scene/Login/VC/LoginVC.swift
  iOS/Sources/Presentation/Scene/Login/View/WaveView.swift
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/View/ClubTypeSegmentedControl.swift
  iOS/Sources/Presentation/Scene/OnBoarding/VC/OnBoardingVC.swift
  iOS/Sources/Presentation/Utils/Extensions/UIKit/UINavigation/UINavigationExt.swift
Labels: 0️⃣Priority: Critical, ✨ Feature, 📬 API

#51 🔀 :: Login page에 테스트코드
  .package.resolved
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Service/Sources/Data/DataSource/Remote/DataSource/AuthRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ClubRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ImageRemote.swift
  Service/Sources/Data/Repositories/DefaultAuthRepository.swift
  Service/Sources/Data/Repositories/DefaultClubRepository.swift
  Service/Sources/Data/Utils/DateUtil.swift
  Service/Sources/Domain/Repositories/AuthRepository.swift
  Service/Sources/Domain/Repositories/ClubRepository.swift
  Service/Sources/Domain/UseCases/Auth/CheckIsLoginedUseCase.swift
  Service/Sources/Domain/UseCases/Auth/CheckIsVerifiedUseCase.swift
  Service/Sources/Domain/UseCases/Auth/LoginUseCase.swift
  Service/Sources/Domain/UseCases/Auth/RegisterUseCase.swift
  Service/Sources/Domain/UseCases/Auth/SendVerifyUseCase.swift
  Service/Sources/Domain/UseCases/Club/ClubCloseUseCase.swift
  Service/Sources/Domain/UseCases/Club/ClubOpenUseCase.swift
  Service/Sources/Domain/UseCases/Club/CreateNewClubUseCase.swift
  Service/Sources/Domain/UseCases/Club/DeleteClubUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchClubApplicantUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchClubListUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchClubMemberUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchDetailClubUseCase.swift
  Service/Sources/Domain/UseCases/Club/UpdateClubUseCase.swift
  Service/Sources/Domain/UseCases/Club/UserAcceptUseCase.swift
  Service/Sources/Domain/UseCases/Club/UserKickUseCase.swift
  Service/Sources/Domain/UseCases/Club/UserRejectUseCase.swift
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/Excutable.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Sources/Presentation/Scene/Login/Reactor/LoginReactor.swift
  iOS/Support/Info.plist
  iOS/Tests/Mock/MockFailureAuthRepository.swift
  iOS/Tests/Mock/MockSuccessAuthRepository.swift
  iOS/Tests/Reactor/LoginReactorSpec.swift
Labels: ✅ Test, 3️⃣Priority: Low

#53 🔀 :: AuthAPI Verify Param 변경
  Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
  Service/Sources/Data/DataSource/Remote/DataSource/AuthRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ImageRemote.swift
  Service/Sources/Data/Repositories/DefaultAuthRepository.swift
  Service/Sources/Data/Repositories/DefaultImageRepository.swift
  Service/Sources/Domain/Repositories/AuthRepository.swift
  Service/Sources/Domain/Repositories/ImageRepository.swift
  Service/Sources/Domain/UseCases/Auth/CheckIsVerifiedUseCase.swift
  Service/Sources/Domain/UseCases/Auth/SendVerifyUseCase.swift
  iOS/Tests/Mock/MockFailureAuthRepository.swift
  iOS/Tests/Mock/MockSuccessAuthRepository.swift
Labels: 1️⃣Priority: High, 📬 API

#54 🔀 :: Dummy Entity 방식 변경
  Service/Sources/Domain/Entities/Club.swift
  Service/Sources/Domain/Entities/ClubList.swift
  Service/Sources/Domain/Entities/RelatedLink.swift
  Service/Sources/Domain/Entities/User.swift
  iOS/Sources/Presentation/Scene/Main/Accept/Reactor/AcceptReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/MemberAppend/Reactor/MemberAppendReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/Reactor/MyPageReactor.swift
Labels: 3️⃣Priority: Low, 🔨 Refactor
