Repository GSM-MSG/GCMS-iOS, pull requests merged in 2022-06, with the labels that each got.

#92 🔀 :: 동아리 수정할 때 빈 값을 보내는 오류 수정
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/DetailClub/DetailClubResponse.swift
  Service/Sources/Domain/Entities/Club.swift
  Service/Sources/Domain/UseCases/Image/UploadImagesUseCase.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/VC/SecondUpdateClubVC.swift
Labels: 0️⃣Priority: Critical, 🐞 BugFix

#95 🔀 :: 동아리 멤버 바인딩
  Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/Reactor/ClubMemberReactor.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/VC/ClubMemberVC.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/ApplicantCell.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/MemberHeaderView.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/StatusMemberCell.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/VC/MyPageVC.swift
Labels: 2️⃣Priority: Medium, 📬 API, 🔨 Refactor

#96 🔀 :: 동아리 생성/수정할때 제목에 정규식 적용
  iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift
  iOS/Sources/Presentation/Utils/Extensions/Swift/StringExt.swift
Labels: 0️⃣Priority: Critical, 📬 API, 🔨 Refactor

#97 🔀 :: OfflineCache doOnNeedRefresh 로직 변경
  Service/Sources/Data/DataSource/Local/DataSource/ClubLocal.swift
  Service/Sources/Data/Repositories/DefaultClubRepository.swift
Labels: 3️⃣Priority: Low, 🔨 Refactor

#100 🔀 :: relatedLink -> notionLink
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/DetailClub/DetailClubDTO.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/DetailClub/DetailClubResponse.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/NewClub/NewClubRequest.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/RelatedLinkDTO.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/UpdateClub/UpdateClubRequest.swift
  Service/Sources/Domain/Entities/Club.swift
  Service/Sources/Domain/Entities/RelatedLink.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/VC/SecondNewClubVC.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/VC/SecondUpdateClubVC.swift
Labels: 0️⃣Priority: Critical, 📬 API

#102 🔀 :: 방과후 신청 페이지 삭제
  Service/Sources/DI/RepositoryAssembly.swift
  Service/Sources/DI/UseCaseAssembly.swift
  Service/Sources/Data/DataSource/Remote/API/AfterSchoolAPI.swift
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/AfterSchool/AfterSchoolDTO.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/AfterSchool/AfterSchoolList/AfterSchoolListResponse.swift
  Service/Sources/Data/DataSource/Remote/DataSource/AfterSchoolRemote.swift
  Service/Sources/Data/Repositories/DefaultAfterSchoolRepository.swift
  Service/Sources/Domain/Entities/AfterSchool.swift
  Service/Sources/Domain/Enums/AfterSchoolSeason.swift
  Service/Sources/Domain/Enums/AfterSchoolWeek.swift
  Service/Sources/Domain/Parameters/AfterSchoolQuery.swift
  Service/Sources/Domain/Repositories/AfterSchoolRepository.swift
  Service/Sources/Domain/UseCases/AfterSchool/ApplyAfterSchoolUseCase.swift
  Service/Sources/Domain/UseCases/AfterSchool/CancelAfterSchoolUseCase.swift
  Service/Sources/Domain/UseCases/AfterSchool/FetchAfterSchoolListUseCase.swift
  Service/Sources/Domain/UseCases/AfterSchool/FetchFindAfterSchoolUseCase.swift
  iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
  iOS/Sources/Application/DI/Assembly/VCAssembly.swift
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/Reactor/AfterSchoolReactor.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/SearchFilter/Reactor/SearchFilterReactor.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/SearchFilter/VC/SearchFilterVC.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/SearchFilter/View/FilterModalSegmentedControl.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/SearchFilter/View/SegmentHeaderLabel.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/VC/AfterSchoolVC.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/View/Cell/AfterSchoolTableViewCell.swift
  iOS/Sources/Presentation/Scene/Main/AfterSchool/View/SemiBoldTextLabel.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
Labels: 0️⃣Priority: Critical, ✨ Feature, 🔨 Refactor

#104 🔀 :: Request보낼 때 DELTE인 method를 POST로 변경
  Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
  Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
Labels: 1️⃣Priority: High, 📬 API

#106 mainVC 리팩토링
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
Labels: 1️⃣Priority: High, 🐞 BugFix

#110 🔀 :: redesign/UpdateClub
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/UpdateClub/UpdateClubRequest.swift
  iOS/Sources/Application/Flow/Flows/Main/MainFlow.swift
  iOS/Sources/Application/Flow/Step/GCMSStep.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/VC/ThirdNewClubVC.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/VC/FirstUpdateClubVC.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/VC/SecondUpdateClubVC.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/VC/ThirdUpdateClubVC.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/View/UpdateClubSteppedProgressBar.swift
Labels: 1️⃣Priority: High, 🔨 Refactor

#112 🔀 :: HomeVC redesign
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/EditorialClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/FreedomClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Items/MajorClubListVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/View/Layout/GCMSLayout.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/VC/SecondNewClubVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/VC/ThirdNewClubVC.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/VC/FirstUpdateClubVC.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/VC/SecondUpdateClubVC.swift
Labels: 3️⃣Priority: Low, 🔨 Refactor

#113 🔀 :: 메모리 아끼기!
  iOS/Sources/Presentation/Scene/Main/Common/Cell/ClubListCell.swift
  iOS/Sources/Presentation/Scene/Main/Common/ClubView.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
Labels: 3️⃣Priority: Low, 🔨 Refactor

#114 🔀 :: cell에서 prepareForReuse가 불러지면 이미지 다운로드는 cancel합니다
  iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/ApplicantCell.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/StatusMemberCell.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/View/Cell/ClubMemberCell.swift
  iOS/Sources/Presentation/Scene/Main/MemberAppend/View/Cell/StudentCell.swift
Labels: 3️⃣Priority: Low, 🔨 Refactor

#115 🔀 :: delete route / -> /delete
  Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
Labels: 0️⃣Priority: Critical, 🐞 BugFix, 📬 API

#124 🔀 :: 애플 로그인에 기능 추가
  Service/Sources/DI/UseCaseAssembly.swift
  Service/Sources/Data/DataSource/Local/Keychain/Keychain.swift
  Service/Sources/Data/DataSource/Local/Keychain/KeychainLocal.swift
  Service/Sources/Data/DataSource/Local/UserDefaults/UserDefaultsLocal.swift
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Service/Sources/Data/DataSource/Remote/API/GuestAPI.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Guest/GuestRefreshTokenResponse.swift
  Service/Sources/Data/DataSource/Remote/DataSource/GuestRemote.swift
  Service/Sources/Data/Repositories/DefaultGuestRepository.swift
  Service/Sources/Domain/Repositories/GuestRepository.swift
  Service/Sources/Domain/UseCases/Auth/CheckIsLoginedUseCase.swift
  Service/Sources/Domain/UseCases/Guest/IssueGuestTokenUseCase.swift
  Service/Sources/Domain/UseCases/Guest/RevokeGuestTokenUseCase.swift
  iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/VC/OnBoardingVC.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift
Labels: 0️⃣Priority: Critical, 🌏 Deploy, 📬 API

#117 🔀 :: Reactor/Club
  iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/VC/FirstUpdateClubVC.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/VC/SecondUpdateClubVC.swift
Labels: 1️⃣Priority: High, 🔨 Refactor

#125 🔀 :: feat/Privacy
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/Reactor/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/VC/OnBoardingVC.swift
Labels: 1️⃣Priority: High, 🌏 Deploy, ✨ Feature, 🔨 Refactor

#126 🔀 :: ReDesign OnboardingVC
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/VC/OnBoardingVC.swift
Labels: 0️⃣Priority: Critical, 🔨 Refactor

#127 🔀 :: feat/errorMapping
  Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
  Service/Sources/Data/DataSource/Remote/API/GuestAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
  Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
  Service/Sources/Domain/Error/GCMSError.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/Reactor/ClubMemberReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift
Labels: 0️⃣Priority: Critical, 🌏 Deploy, ✨ Feature, 🔨 Refactor
