Repository GSM-MSG/GCMS-iOS, pull requests merged in 2023-04, with the labels that each got.

#184 🔀 :: Tuist Version 업그레이드
  .tuist-version
Labels: ⚙ Setting

#187 🔀 :: 마이페이지 프로필이미지 디자인과 다른 부분 수정
  iOS/Derived/Sources/TuistAssets+GCMS.swift
  iOS/Derived/Sources/TuistFonts+GCMS.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/View/UserProfileView.swift
Labels: 🔨 Refactor

#188 🔀 :: 싱글톤으로 덕지덕지 이루어져있던 DataSource들을 DI 패턴으로 바꿉니다
  Service/Sources/DI/DataSourceAssembly.swift
  Service/Sources/DI/RepositoryAssembly.swift
  Service/Sources/Data/DataSource/Local/DataSource/ClubLocal.swift
  Service/Sources/Data/DataSource/Local/Keychain/KeychainLocal.swift
  Service/Sources/Data/DataSource/Local/Realm/RealmTask.swift
  Service/Sources/Data/DataSource/Remote/DataSource/AuthRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ClubApplicantRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ClubMemberRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ClubRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ImageRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/UserRemote.swift
  Service/Sources/Data/DataSource/Remote/Plugin/JWTPlugin.swift
  Service/Sources/Data/Repositories/DefaultAuthRepository.swift
  Service/Sources/Data/Repositories/DefaultClubApplicantRepository.swift
  Service/Sources/Data/Repositories/DefaultClubMemberRepository.swift
  Service/Sources/Data/Repositories/DefaultClubRepository.swift
  Service/Sources/Data/Repositories/DefaultImageRepository.swift
  Service/Sources/Data/Repositories/DefaultUserRepository.swift
  iOS/Sources/Application/AppDelegate.swift
Labels: 1️⃣Priority: High, 🔨 Refactor
