Repository GSM-MSG/GCMS-iOS, pull requests merged in 2023-03, with the labels that each got.

#167 🔀 :: 게스트로그인 관련된 내용 다 지우기
  Service/Sources/Data/DataSource/Local/Keychain/Keychain.swift
  Service/Sources/Data/DataSource/Local/Keychain/KeychainLocal.swift
  Service/Sources/Data/DataSource/Local/UserDefaults/UserDefaultsLocal.swift
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Service/Sources/Domain/Error/GCMSError.swift
  Service/Sources/Domain/UseCases/Auth/CheckIsLoginedUseCase.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/OnBoardingVC.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/DetailClubVC.swift
  iOS/Sources/Presentation/Scene/Main/Home/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/HomeVC.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/MyPageVC.swift
  iOS/Sources/Presentation/Utils/Extensions/Rx/ASAuthorizationAppleID+Rx.swift
  iOS/Sources/Presentation/Utils/Extensions/Rx/ASAuthorizationControllerProxy.swift
  iOS/Support/GCMS.entitlements
Labels: 3️⃣Priority: Low, 🔨 Refactor

#169 🔀 :: textField 공백이랑 enter 체크
  iOS/Sources/Presentation/Scene/Main/NewClub/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/Update/UpdateClubReactor.swift
  iOS/Sources/Presentation/Utils/Extensions/Swift/StringExt.swift
Labels: 3️⃣Priority: Low, 🔨 Refactor

#171 🔀 :: 어떨결에 에러 메세지만 바꿈
  Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
  Service/Sources/Domain/Error/GCMSError.swift
  iOS/Sources/Presentation/Scene/Main/Update/UpdateClubReactor.swift
Labels: 0️⃣Priority: Critical, 📬 API, 🔨 Refactor

#176 🔀 :: bannerImage에 gradient 추가
  iOS/Sources/Presentation/Scene/Main/DetailClub/DetailClubVC.swift
  iOS/Sources/Presentation/Utils/Extensions/UIKit/UIView/UIViewExt.swift
Labels: 1️⃣Priority: High, 🔨 Refactor

#177 🔀 :: 마이페이지버튼 마이프로필이미지로 변경
  .package.resolved
  Service/Sources/DI/UseCaseAssembly.swift
  Service/Sources/Domain/UseCases/User/FetchMiniProfileUseCase.swift
  iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
  iOS/Sources/Presentation/Scene/Main/Home/HomeReactor.swift
  iOS/Sources/Presentation/Scene/Main/Home/HomeVC.swift
Labels: 1️⃣Priority: High, ✨ Feature

#181 🔀:: 로그인 부분 Auth 디자인과 다른 부분 수정
  .package.resolved
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/OnBoardingVC.swift
Labels: 3️⃣Priority: Low, 🔨 Refactor
