Repository GSM-MSG/GCMS-iOS, pull requests merged in 2023-02, with the labels that each got.

#146 🔀 :: CI 성능 개선
  .github/workflows/CI.yml
  .github/workflows/CachingTuistDependencies.yml
  .github/workflows/pr.yml
  .github/workflows/swift.yml
  .gitignore
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: 1️⃣Priority: High, ⚙ Setting

#150 🔀 :: XCConfig 추가
  .gitignore
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Tuist/ProjectDescriptionHelpers/DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/Excutable.swift
  Tuist/ProjectDescriptionHelpers/PathExtension.swift
  Tuist/ProjectDescriptionHelpers/ProjectDeployTarget.swift
  iOS/Project.swift
Labels: 0️⃣Priority: Critical, ✨ Feature

#148 🔀:: clubMember-api-change
  Service/Sources/DI/UseCaseAssembly.swift
  Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Service/Sources/Data/DataSource/Remote/API/GuestAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
  Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Club/Member/MemberDTO.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ClubMemberRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/ClubRemote.swift
  Service/Sources/Data/Repositories/DefaultClubMemberRepository.swift
  Service/Sources/Data/Repositories/DefaultClubRepository.swift
  Service/Sources/Domain/Entities/Member.swift
  Service/Sources/Domain/Error/ClubMemberError.swift
  Service/Sources/Domain/Repositories/ClubMemberRepository.swift
  Service/Sources/Domain/Repositories/ClubRepository.swift
  Service/Sources/Domain/UseCases/Club/ClubDelegationUseCase.swift
  Service/Sources/Domain/UseCases/Club/FetchClubMemberUseCase.swift
  Service/Sources/Domain/UseCases/Club/UserKickUseCase.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/ClubMemberReactor.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/StatusMemberCell.swift
Labels: 1️⃣Priority: High, 🔨 Refactor

#152 🔀 :: GAuth로 로그인 변경
  Service/Sources/Data/DataSource/Local/Keychain/KeychainLocal.swift
  Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
  Service/Sources/Data/DataSource/Remote/DataMapping/Token/TokenDTO.swift
  Service/Sources/Data/DataSource/Remote/DataSource/AuthRemote.swift
  Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
  Service/Sources/Data/DataSource/Remote/Plugin/JWTPlugin.swift
  Service/Sources/Data/Repositories/DefaultAuthRepository.swift
  Service/Sources/Data/Utils/DateUtil.swift
  Service/Sources/Domain/Repositories/AuthRepository.swift
  Service/Sources/Domain/UseCases/Auth/LoginUseCase.swift
  ThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/OnBoardingVC.swift
Labels: 0️⃣Priority: Critical, ✨ Feature, 📬 API

#159 🔀:: api-error-add
  .package.resolved
  Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ClubApplicantAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
  Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
  Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
  Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
  Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
  Service/Sources/Domain/Error/ClubApplicantError.swift
  Service/Sources/Domain/Error/ClubMemberError.swift
  Service/Sources/Domain/Error/GCMSError.swift
  iOS/Sources/Presentation/Scene/Auth/OnBoarding/OnBoardingReactor.swift
  iOS/Sources/Presentation/Scene/Main/ClubMember/ClubMemberReactor.swift
  iOS/Sources/Presentation/Scene/Main/DetailClub/DetailClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/MyPageReactor.swift
  iOS/Sources/Presentation/Scene/Main/MyPage/MyPageVC.swift
  iOS/Sources/Presentation/Scene/Main/NewClub/NewClubReactor.swift
  iOS/Sources/Presentation/Scene/Main/Update/UpdateClubReactor.swift
  iOS/Sources/Presentation/Utils/Extensions/Swift/ErrorExt.swift
Labels: 2️⃣Priority: Medium, 🔨 Refactor

#161 🔀 :: Realm 데이터베이스 마이그레이션
  Service/Sources/Data/DataSource/Local/Realm/RealmTask.swift
Labels: 0️⃣Priority: Critical, 🐞 BugFix
